// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/submission_service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	entity "github.com/an-halim/golang-advanced/assignment-1/entity"
	request "github.com/an-halim/golang-advanced/assignment-1/request"
	response "github.com/an-halim/golang-advanced/assignment-1/response"
	gomock "github.com/golang/mock/gomock"
)

// MockISubmissionService is a mock of ISubmissionService interface.
type MockISubmissionService struct {
	ctrl     *gomock.Controller
	recorder *MockISubmissionServiceMockRecorder
}

// MockISubmissionServiceMockRecorder is the mock recorder for MockISubmissionService.
type MockISubmissionServiceMockRecorder struct {
	mock *MockISubmissionService
}

// NewMockISubmissionService creates a new mock instance.
func NewMockISubmissionService(ctrl *gomock.Controller) *MockISubmissionService {
	mock := &MockISubmissionService{ctrl: ctrl}
	mock.recorder = &MockISubmissionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISubmissionService) EXPECT() *MockISubmissionServiceMockRecorder {
	return m.recorder
}

// CreateSubmission mocks base method.
func (m *MockISubmissionService) CreateSubmission(ctx context.Context, request request.CreateSubmissionInfo) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubmission", ctx, request)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubmission indicates an expected call of CreateSubmission.
func (mr *MockISubmissionServiceMockRecorder) CreateSubmission(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubmission", reflect.TypeOf((*MockISubmissionService)(nil).CreateSubmission), ctx, request)
}

// DeleteSubmission mocks base method.
func (m *MockISubmissionService) DeleteSubmission(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubmission", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubmission indicates an expected call of DeleteSubmission.
func (mr *MockISubmissionServiceMockRecorder) DeleteSubmission(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubmission", reflect.TypeOf((*MockISubmissionService)(nil).DeleteSubmission), ctx, id)
}

// GetAllSubmission mocks base method.
func (m *MockISubmissionService) GetAllSubmission(ctx context.Context, pageSize, page int) ([]entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubmission", ctx, pageSize, page)
	ret0, _ := ret[0].([]entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSubmission indicates an expected call of GetAllSubmission.
func (mr *MockISubmissionServiceMockRecorder) GetAllSubmission(ctx, pageSize, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubmission", reflect.TypeOf((*MockISubmissionService)(nil).GetAllSubmission), ctx, pageSize, page)
}

// GetAllUserSubmission mocks base method.
func (m *MockISubmissionService) GetAllUserSubmission(ctx context.Context, id, pageSize, page int) ([]entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserSubmission", ctx, id, pageSize, page)
	ret0, _ := ret[0].([]entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserSubmission indicates an expected call of GetAllUserSubmission.
func (mr *MockISubmissionServiceMockRecorder) GetAllUserSubmission(ctx, id, pageSize, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserSubmission", reflect.TypeOf((*MockISubmissionService)(nil).GetAllUserSubmission), ctx, id, pageSize, page)
}

// GetSubmissionByID mocks base method.
func (m *MockISubmissionService) GetSubmissionByID(ctx context.Context, id int) (response.GetOneSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmissionByID", ctx, id)
	ret0, _ := ret[0].(response.GetOneSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmissionByID indicates an expected call of GetSubmissionByID.
func (mr *MockISubmissionServiceMockRecorder) GetSubmissionByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmissionByID", reflect.TypeOf((*MockISubmissionService)(nil).GetSubmissionByID), ctx, id)
}

// UpdateSubmission mocks base method.
func (m *MockISubmissionService) UpdateSubmission(ctx context.Context, id int, submission entity.Submission) (entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubmission", ctx, id, submission)
	ret0, _ := ret[0].(entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubmission indicates an expected call of UpdateSubmission.
func (mr *MockISubmissionServiceMockRecorder) UpdateSubmission(ctx, id, submission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubmission", reflect.TypeOf((*MockISubmissionService)(nil).UpdateSubmission), ctx, id, submission)
}

// MockISubmissionRepository is a mock of ISubmissionRepository interface.
type MockISubmissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISubmissionRepositoryMockRecorder
}

// MockISubmissionRepositoryMockRecorder is the mock recorder for MockISubmissionRepository.
type MockISubmissionRepositoryMockRecorder struct {
	mock *MockISubmissionRepository
}

// NewMockISubmissionRepository creates a new mock instance.
func NewMockISubmissionRepository(ctrl *gomock.Controller) *MockISubmissionRepository {
	mock := &MockISubmissionRepository{ctrl: ctrl}
	mock.recorder = &MockISubmissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISubmissionRepository) EXPECT() *MockISubmissionRepositoryMockRecorder {
	return m.recorder
}

// CreateSubmission mocks base method.
func (m *MockISubmissionRepository) CreateSubmission(ctx context.Context, submission *entity.Submission) (entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubmission", ctx, submission)
	ret0, _ := ret[0].(entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubmission indicates an expected call of CreateSubmission.
func (mr *MockISubmissionRepositoryMockRecorder) CreateSubmission(ctx, submission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubmission", reflect.TypeOf((*MockISubmissionRepository)(nil).CreateSubmission), ctx, submission)
}

// DeleteSubmission mocks base method.
func (m *MockISubmissionRepository) DeleteSubmission(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubmission", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubmission indicates an expected call of DeleteSubmission.
func (mr *MockISubmissionRepositoryMockRecorder) DeleteSubmission(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubmission", reflect.TypeOf((*MockISubmissionRepository)(nil).DeleteSubmission), ctx, id)
}

// GetAllSubmission mocks base method.
func (m *MockISubmissionRepository) GetAllSubmission(ctx context.Context, pageSize, page int) ([]entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubmission", ctx, pageSize, page)
	ret0, _ := ret[0].([]entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSubmission indicates an expected call of GetAllSubmission.
func (mr *MockISubmissionRepositoryMockRecorder) GetAllSubmission(ctx, pageSize, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubmission", reflect.TypeOf((*MockISubmissionRepository)(nil).GetAllSubmission), ctx, pageSize, page)
}

// GetAllUserSubmission mocks base method.
func (m *MockISubmissionRepository) GetAllUserSubmission(ctx context.Context, id, pageSize, page int) ([]entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserSubmission", ctx, id, pageSize, page)
	ret0, _ := ret[0].([]entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserSubmission indicates an expected call of GetAllUserSubmission.
func (mr *MockISubmissionRepositoryMockRecorder) GetAllUserSubmission(ctx, id, pageSize, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserSubmission", reflect.TypeOf((*MockISubmissionRepository)(nil).GetAllUserSubmission), ctx, id, pageSize, page)
}

// GetSubmissionByID mocks base method.
func (m *MockISubmissionRepository) GetSubmissionByID(ctx context.Context, id int) (entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmissionByID", ctx, id)
	ret0, _ := ret[0].(entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmissionByID indicates an expected call of GetSubmissionByID.
func (mr *MockISubmissionRepositoryMockRecorder) GetSubmissionByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmissionByID", reflect.TypeOf((*MockISubmissionRepository)(nil).GetSubmissionByID), ctx, id)
}

// UpdateSubmission mocks base method.
func (m *MockISubmissionRepository) UpdateSubmission(ctx context.Context, id int, submission entity.Submission) (entity.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubmission", ctx, id, submission)
	ret0, _ := ret[0].(entity.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubmission indicates an expected call of UpdateSubmission.
func (mr *MockISubmissionRepositoryMockRecorder) UpdateSubmission(ctx, id, submission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubmission", reflect.TypeOf((*MockISubmissionRepository)(nil).UpdateSubmission), ctx, id, submission)
}
